### ISSUE TITLE
revise html-conduit-1.2.1.2 to use tagstream < 0.5.6 for ghc < 8.3

### ISSUE THREAD

**Issue by juhp** [snoyberg/xml#165]
html-conduit-1.2.1.2 fails to build on ghc-8.2.2 with tagstream-conduit-0.5.6:

```
Configuring tagstream-conduit-0.5.6...
Building tagstream-conduit-0.5.6...
Installed tagstream-conduit-0.5.6
Downloading html-conduit-1.2.1.2...
Configuring html-conduit-1.2.1.2...
Building html-conduit-1.2.1.2...
Failed to install html-conduit-1.2.1.2
Build log ( /builddir/build/BUILD/dl-rhel-0.2.1/.cabal-sandbox/logs/ghc-8.2.2/html-conduit-1.2.1.2-7fVRdSoHmkqLnSTTlVNaDV.log ):
cabal: Entering directory '/tmp/cabal-tmp-2766/html-conduit-1.2.1.2'
Configuring html-conduit-1.2.1.2...
Preprocessing library for html-conduit-1.2.1.2..
Building library for html-conduit-1.2.1.2..
[1 of 1] Compiling Text.HTML.DOM    ( Text/HTML/DOM.hs, dist/dist-sandbox-87762b84/build/Text/HTML/DOM.o )
Text/HTML/DOM.hs:47:5: error:
    * Could not deduce (Control.Monad.Fail.MonadFail m)
        arising from a use of `TS.tokenStream'
      from the context: Monad m
        bound by the type signature for:
                   eventConduit' :: forall (m :: * -> *).
                                    Monad m =>
                                    Conduit T.Text m XT.Event
        at Text/HTML/DOM.hs:45:1-53
      Possible fix:
        add (Control.Monad.Fail.MonadFail m) to the context of
          the type signature for:
            eventConduit' :: forall (m :: * -> *).
                             Monad m =>
                             Conduit T.Text m XT.Event
    * In the first argument of `(=$=)', namely `TS.tokenStream'
      In the expression: TS.tokenStream =$= go []
      In an equation for eventConduit':
          eventConduit'
            = TS.tokenStream =$= go []
            where
                go stack
                  = do mx <- await
                       ....
                toName l = X.Name l Nothing Nothing
                closeStack = mapM_ (yield . XT.EventEndElement)
                isVoid = flip Set.member $ Set.fromList ["area", ....]
   |
47 |     TS.tokenStream =$= go []
   |     ^^^^^^^^^^^^^^
```

Yeah the answer may be why not use a newer version of html-conduit... but for some reason the old version of cabal-install I have for RHEL8 is choosing older library versions...

I think all that is needed to fix this would be a Hackage revision to html-conduit-1.2.1.2 with:

```
  if impl(ghc < 8.3)
    build-depends:     tagstream-conduit < 0.5.6
```

**Comment by snoyberg** [comment]
I’m happy to make you a Hackage maintainer so you can make the tweaks you want. What’s your Hackage username?

**Comment by juhp** [comment]
I am JensPetersen on Hackage, thanks

**Comment by snoyberg** [comment]
OK you should be able to edit now.

**Comment by juhp** [comment]
Thanks, Michael

Unfortunately it seems Hackage does not allow revisions involving conditionals:

```
Errors

Cannot add or remove 'if' conditionals
```

Hmm I suppose I could upload a 1.2.1.3, though it might be too much - I will ponder on it for a while...
