### ISSUE TITLE
xml-hamlet: cannot compile with ghc-8.8 because of MonadFail 

### ISSUE THREAD

**Issue by jwaldmann** [snoyberg/xml#147]
(similar to https://github.com/yesodweb/shakespeare/issues/239 )

```
xml-hamlet   > Building library for xml-hamlet-0.5.0..
xml-hamlet   > [1 of 2] Compiling Text.Hamlet.XMLParse
xml-hamlet   >          
xml-hamlet   > /tmp/stack-b1de27cae1d5b66b/xml-hamlet-0.5.0/Text/Hamlet/XMLParse.hs:28:5: error:
xml-hamlet   >     ‘fail’ is not a (visible) method of class ‘Monad’
```

**Comment by jwaldmann** [comment]
Thanks!
